# Generated by Django 5.1.4 on 2025-01-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
