# Generated by Django 5.1.4 on 2025-01-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_modal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modal',
            new_name='modal_number',
        ),
    ]
