# Generated by Django 5.1.4 on 2025-01-15 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('first_name', models.CharField(default='Delivery First Name', max_length=100)),
                ('last_name', models.CharField(default='Delivery Last Name', max_length=100)),
                ('email', models.CharField(default='Delivery Email', max_length=100)),
                ('phone', models.CharField(default='Delivery Phone', max_length=100)),
                ('address', models.CharField(default='Delivery Address', max_length=100)),
                ('city', models.CharField(default='Delivery City', max_length=100)),
                ('state', models.CharField(default='Delivery State', max_length=100)),
                ('payment_method', models.CharField(default='cash on Delivery', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
