# Generated by Django 5.1.4 on 2025-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quanity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
